repos:
-   repo: https://github.com/adamchainz/django-upgrade
    rev: "1.10.0"
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.1"]
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black